root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"
env_files = [".env"]

[build]
  args_bin = []
  entrypoint = ["./tmp/mini-bili"]
  cmd = "go build -buildvcs=false -o ./tmp/mini-bili ./cmd/mini-bili"
  delay = 500
  exclude_dir = ["tmp","vendor","testdata",".git","cakecake-vue","bin","node_modules"]
  exclude_file = []
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go","mod","sum"]
  kill_delay = "2s"
  log = "tmp/air-build-errors.log"
  poll = false
  rerun = false
  send_interrupt = true
  stop_on_error = true

[build.windows]
  entrypoint = ["./tmp/mini-bili.exe"]
  cmd = "go build -buildvcs=false -o ./tmp/mini-bili.exe ./cmd/mini-bili"
  env = ["GO111MODULE=on", "GOCACHE=D:/Minibili/.gocache"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
