codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 5%

flags:
  frontend:
    paths:
      - cakecake-vue/bilibili-vue/src/
    carryforward: true
  backend:
    paths:
      - internal/
    carryforward: true

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
