-- +goose Up
-- Baseline DDL: all domain tables exported from MySQL via SHOW CREATE TABLE.
-- Goose internal tables (goose_db_version) excluded — goose manages those.
-- Generated by: go run scripts/export_baseline.go > migrations/00001_baseline.sql

CREATE TABLE IF NOT EXISTS `admins` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password_hash` varchar(128) NOT NULL,
  `display_name` varchar(64) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `last_login_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_admins_username` (`username`),
  KEY `idx_admins_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `agent_profiles` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(32) NOT NULL,
  `bot_user_id` bigint unsigned NOT NULL,
  `display_name` varchar(64) NOT NULL,
  `avatar_url` varchar(1024) DEFAULT NULL,
  `sign` varchar(500) DEFAULT NULL,
  `system_prompt` text NOT NULL,
  `welcome_messages_json` text NOT NULL,
  `sort_order` bigint NOT NULL DEFAULT '0',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_agent_profiles_slug` (`slug`),
  KEY `idx_agent_profiles_bot_user_id` (`bot_user_id`),
  KEY `idx_agent_profiles_sort_order` (`sort_order`),
  KEY `idx_agent_profiles_enabled` (`enabled`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `agent_settings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `display_name` varchar(64) NOT NULL,
  `avatar_url` varchar(1024) DEFAULT NULL,
  `sign` varchar(500) DEFAULT NULL,
  `system_prompt` text NOT NULL,
  `welcome_message` varchar(500) NOT NULL,
  `assistant_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `article_coins` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `article_id` bigint unsigned NOT NULL,
  `amount` bigint NOT NULL DEFAULT '1',
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_article_coin_user_article` (`user_id`,`article_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `article_comment_dislikes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `comment_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_article_cmt_dislike_user_cmt` (`user_id`,`comment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `article_comment_likes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `comment_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_article_cmt_like_user_cmt` (`user_id`,`comment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `article_comments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `article_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned DEFAULT '0',
  `level` bigint NOT NULL,
  `content` varchar(2000) NOT NULL,
  `like_count` bigint unsigned DEFAULT '0',
  `pinned` tinyint(1) DEFAULT '0',
  `ip_location` varchar(32) NOT NULL DEFAULT '',
  `created_at` datetime(3) DEFAULT NULL,
  `approved` tinyint(1) NOT NULL DEFAULT '0',
  `curated_ignored` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_article_comment_article` (`article_id`),
  KEY `idx_article_comments_user_id` (`user_id`),
  KEY `idx_article_comments_parent_id` (`parent_id`),
  KEY `idx_article_comments_pinned` (`pinned`),
  KEY `idx_article_comments_curated_ignored` (`curated_ignored`),
  KEY `idx_article_comments_approved` (`approved`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `article_favorites` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `article_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_article_fav_user_article` (`user_id`,`article_id`)
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `article_view_histories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `article_id` bigint unsigned NOT NULL,
  `device` varchar(16) NOT NULL DEFAULT 'web',
  `viewed_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_view_hist_user_article` (`user_id`,`article_id`),
  KEY `idx_view_hist_art_user_viewed` (`viewed_at`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `articles` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `title` varchar(80) NOT NULL,
  `cover_url` varchar(1024) DEFAULT NULL,
  `body_md` longtext NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `tags_json` text,
  `view_count` bigint unsigned DEFAULT '0',
  `comment_count` bigint unsigned DEFAULT '0',
  `coin_count` bigint unsigned DEFAULT '0',
  `fav_count` bigint unsigned DEFAULT '0',
  `forward_count` bigint unsigned DEFAULT '0',
  `published_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `comments_curated` tinyint(1) NOT NULL DEFAULT '0',
  `comments_closed` tinyint(1) NOT NULL DEFAULT '0',
  `fail_reason` varchar(2000) DEFAULT NULL,
  `reviewed_at` datetime(3) DEFAULT NULL,
  `reviewed_by_admin_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_article_user` (`user_id`),
  KEY `idx_article_status` (`status`),
  KEY `idx_article_created` (`created_at`),
  KEY `idx_articles_reviewed_by_admin_id` (`reviewed_by_admin_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `coin_ledgers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `delta_tenths` bigint NOT NULL,
  `reason_type` varchar(32) NOT NULL,
  `video_id` bigint unsigned NOT NULL DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_coin_ledgers_reason_type` (`reason_type`),
  KEY `idx_coin_ledgers_video_id` (`video_id`),
  KEY `idx_coin_ledger_user_created` (`user_id`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `comment_dislikes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `comment_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_dislike_user_comment` (`user_id`,`comment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `comment_likes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `comment_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_like_user_comment` (`user_id`,`comment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=190 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `comments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `video_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned DEFAULT '0',
  `level` bigint NOT NULL,
  `content` varchar(2000) NOT NULL,
  `like_count` bigint unsigned DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  `pinned` tinyint(1) DEFAULT '0',
  `ip_location` varchar(32) NOT NULL DEFAULT '',
  `approved` tinyint(1) NOT NULL DEFAULT '0',
  `curated_ignored` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_comment_video` (`video_id`),
  KEY `idx_comments_user_id` (`user_id`),
  KEY `idx_comments_parent_id` (`parent_id`),
  KEY `idx_comments_pinned` (`pinned`),
  KEY `idx_comments_approved` (`approved`),
  KEY `idx_comments_curated_ignored` (`curated_ignored`)
) ENGINE=InnoDB AUTO_INCREMENT=99 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `danmaku_likes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `danmaku_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_danmaku_like_user_dm` (`user_id`,`danmaku_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `danmakus` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `video_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `content` varchar(400) NOT NULL,
  `color` varchar(16) NOT NULL,
  `type` varchar(16) NOT NULL,
  `video_time` double NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `like_count` bigint unsigned DEFAULT '0',
  `font_size` varchar(8) NOT NULL DEFAULT 'md',
  PRIMARY KEY (`id`),
  KEY `idx_danmaku_video` (`video_id`),
  KEY `idx_danmakus_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `dm_conversations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_low` bigint unsigned NOT NULL,
  `user_high` bigint unsigned NOT NULL,
  `last_message_at` datetime(3) DEFAULT NULL,
  `last_preview` varchar(500) DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `kind` varchar(16) NOT NULL DEFAULT 'human',
  `agent_profile_id` bigint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_dm_pair_low_high` (`user_low`,`user_high`),
  KEY `idx_dm_conversations_last_message_at` (`last_message_at`),
  KEY `idx_dm_conversations_kind` (`kind`),
  KEY `idx_dm_conversations_agent_profile_id` (`agent_profile_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `dm_messages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `conversation_id` bigint unsigned NOT NULL,
  `sender_id` bigint unsigned NOT NULL,
  `content` varchar(500) NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `role` varchar(16) NOT NULL DEFAULT '',
  `tool_activities` text,
  `tool_result_data` text,
  PRIMARY KEY (`id`),
  KEY `idx_dm_msg_conv` (`conversation_id`),
  KEY `idx_dm_messages_sender_id` (`sender_id`),
  KEY `idx_dm_messages_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=345 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `dm_participants` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `conversation_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `unread_count` int unsigned NOT NULL DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `pinned` tinyint(1) NOT NULL DEFAULT '0',
  `pinned_at` datetime(3) DEFAULT NULL,
  `muted` tinyint(1) NOT NULL DEFAULT '0',
  `hidden_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_dm_part_user_conv` (`conversation_id`,`user_id`),
  KEY `idx_dm_participants_user_id` (`user_id`),
  KEY `idx_dm_participants_pinned_at` (`pinned_at`),
  KEY `idx_dm_participants_hidden_at` (`hidden_at`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `dynamic_comment_dislikes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `comment_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_dyn_cmt_dislike_user_cmt` (`user_id`,`comment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `dynamic_comment_likes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `comment_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_dyn_cmt_like_user_cmt` (`user_id`,`comment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `dynamic_comments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `dynamic_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned NOT NULL DEFAULT '0',
  `level` bigint NOT NULL DEFAULT '1',
  `content` varchar(1000) NOT NULL,
  `like_count` bigint unsigned DEFAULT '0',
  `pinned` tinyint(1) DEFAULT '0',
  `ip_location` varchar(32) NOT NULL DEFAULT '',
  `created_at` datetime(3) DEFAULT NULL,
  `approved` tinyint(1) NOT NULL DEFAULT '0',
  `curated_ignored` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_dynamic_comments_parent_id` (`parent_id`),
  KEY `idx_dynamic_comments_pinned` (`pinned`),
  KEY `idx_dyn_cmt_dynamic` (`dynamic_id`),
  KEY `idx_dynamic_comments_user_id` (`user_id`),
  KEY `idx_dynamic_comments_approved` (`approved`),
  KEY `idx_dynamic_comments_curated_ignored` (`curated_ignored`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `favorite_folders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `title` varchar(20) NOT NULL,
  `description` varchar(200) NOT NULL DEFAULT '',
  `is_public` tinyint(1) NOT NULL DEFAULT '1',
  `is_default` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `cover_url` varchar(1024) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_fav_folder_user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `home_banners` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(120) NOT NULL,
  `image_url` varchar(1024) NOT NULL,
  `link_type` varchar(16) NOT NULL DEFAULT 'none',
  `link_target` varchar(512) DEFAULT NULL,
  `sort_order` bigint NOT NULL DEFAULT '0',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `start_at` datetime(3) DEFAULT NULL,
  `end_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_home_banners_sort_order` (`sort_order`),
  KEY `idx_home_banners_enabled` (`enabled`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `hot_search_display_layouts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_json` text NOT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `hot_search_ops` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `op_type` varchar(16) NOT NULL,
  `keyword` varchar(100) NOT NULL,
  `display_title` varchar(100) DEFAULT NULL,
  `badge` varchar(8) DEFAULT NULL,
  `pin_rank` bigint NOT NULL DEFAULT '0',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `start_at` datetime(3) DEFAULT NULL,
  `end_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hot_search_ops_op_type` (`op_type`),
  KEY `idx_hot_search_ops_pin_rank` (`pin_rank`),
  KEY `idx_hot_search_ops_enabled` (`enabled`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `like_notif_mutes` (
  `recipient_id` bigint unsigned NOT NULL,
  `comment_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  UNIQUE KEY `idx_like_notif_mute_pair` (`recipient_id`,`comment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `recipient_id` bigint unsigned NOT NULL,
  `type` varchar(48) NOT NULL,
  `related_id` bigint unsigned DEFAULT NULL,
  `sender_names_json` text,
  `total_likes` bigint DEFAULT '0',
  `comment_preview` varchar(32) DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `payload_json` text,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_is_read` (`is_read`),
  KEY `idx_notif_recipient` (`recipient_id`),
  KEY `idx_notifications_type` (`type`),
  KEY `idx_notifications_related_id` (`related_id`)
) ENGINE=InnoDB AUTO_INCREMENT=108 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `schema_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `version` bigint NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` varchar(512) DEFAULT NULL,
  `executed_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_schema_versions_version` (`version`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `system_configs` (
  `key` varchar(64) NOT NULL,
  `value` varchar(1024) NOT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_blocks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `blocker_id` bigint unsigned NOT NULL,
  `blocked_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_block_pair` (`blocker_id`,`blocked_id`),
  KEY `idx_user_blocks_blocker_id` (`blocker_id`),
  KEY `idx_user_blocks_blocked_id` (`blocked_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_daily_tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `task_date` varchar(10) NOT NULL,
  `login_done` tinyint(1) NOT NULL DEFAULT '0',
  `watch_done` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_daily_task` (`user_id`,`task_date`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_dynamic_likes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `dynamic_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_dyn_like_user_dyn` (`user_id`,`dynamic_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_dynamics` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `title` varchar(20) NOT NULL DEFAULT '',
  `content` varchar(233) NOT NULL DEFAULT '',
  `images_json` text NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `like_count` bigint unsigned NOT NULL DEFAULT '0',
  `comment_count` bigint unsigned NOT NULL DEFAULT '0',
  `comments_closed` tinyint(1) NOT NULL DEFAULT '0',
  `comments_curated` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_dyn_user_created` (`user_id`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_follow_group_members` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `group_id` bigint unsigned NOT NULL,
  `followee_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_follow_group_member` (`group_id`,`followee_id`),
  KEY `idx_user_follow_group_members_group_id` (`group_id`),
  KEY `idx_user_follow_group_members_followee_id` (`followee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_follow_groups` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `name` varchar(20) NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_follow_group_user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_follows` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `follower_id` bigint unsigned NOT NULL,
  `followee_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_follow_pair` (`follower_id`,`followee_id`),
  KEY `idx_user_follow_follower` (`follower_id`),
  KEY `idx_user_follow_followee` (`followee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `user_search_histories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `keyword` varchar(100) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `keyword_norm` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_search_norm` (`user_id`,`keyword_norm`),
  KEY `idx_user_search_updated` (`updated_at`),
  KEY `idx_user_search_user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11102 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `password_hash` varchar(128) NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `avatar_url` varchar(1024) DEFAULT NULL,
  `cake_id` varchar(36) DEFAULT NULL,
  `nickname` varchar(64) DEFAULT NULL,
  `sign` varchar(500) DEFAULT NULL,
  `gender` varchar(16) DEFAULT NULL,
  `birthday` varchar(10) DEFAULT NULL,
  `deletion_requested_at` datetime(3) DEFAULT NULL,
  `deletion_effective_at` datetime(3) DEFAULT NULL,
  `anonymized_at` datetime(3) DEFAULT NULL,
  `first_published_at` datetime(3) DEFAULT NULL,
  `space_announcement` varchar(600) DEFAULT NULL,
  `privacy_public_favorites` tinyint(1) NOT NULL DEFAULT '0',
  `privacy_public_recent_coins` tinyint(1) NOT NULL DEFAULT '0',
  `privacy_public_following` tinyint(1) NOT NULL DEFAULT '0',
  `privacy_public_fans` tinyint(1) NOT NULL DEFAULT '0',
  `privacy_public_birthday` tinyint(1) NOT NULL DEFAULT '1',
  `experience` bigint unsigned NOT NULL DEFAULT '0',
  `coin_balance_tenths` bigint NOT NULL DEFAULT '230',
  `view_history_paused` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_users_username` (`username`),
  KEY `idx_users_created_at` (`created_at`),
  KEY `idx_users_cake_id` (`cake_id`),
  KEY `idx_users_anonymized_at` (`anonymized_at`),
  KEY `idx_users_deletion_requested_at` (`deletion_requested_at`),
  KEY `idx_users_deletion_effective_at` (`deletion_effective_at`),
  KEY `idx_users_first_published_at` (`first_published_at`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `video_coins` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `video_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `amount` bigint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_video_coin_user_video` (`user_id`,`video_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `video_favorites` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `video_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `folder_id` bigint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_video_fav_user_video_folder` (`user_id`,`video_id`,`folder_id`),
  KEY `idx_video_fav_folder` (`folder_id`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `video_likes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `video_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_video_like_user_video` (`user_id`,`video_id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `video_view_histories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `video_id` bigint unsigned NOT NULL,
  `progress_sec` double NOT NULL DEFAULT '0',
  `duration_sec` double NOT NULL DEFAULT '0',
  `device` varchar(16) NOT NULL DEFAULT 'web',
  `viewed_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_view_hist_user_video` (`user_id`,`video_id`),
  KEY `idx_view_hist_user_viewed` (`viewed_at`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `videos` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `title` varchar(80) NOT NULL,
  `description` varchar(2000) DEFAULT NULL,
  `duration_sec` double DEFAULT NULL,
  `status` varchar(32) DEFAULT NULL,
  `fail_reason` varchar(2000) DEFAULT NULL,
  `video_url` varchar(1024) DEFAULT NULL,
  `cover_url` varchar(1024) DEFAULT NULL,
  `play_count` bigint unsigned DEFAULT '0',
  `danmaku_count` bigint unsigned DEFAULT '0',
  `comment_count` bigint unsigned DEFAULT '0',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `tags_json` text,
  `like_count` bigint unsigned DEFAULT '0',
  `comments_closed` tinyint(1) NOT NULL DEFAULT '0',
  `danmaku_closed` tinyint(1) NOT NULL DEFAULT '0',
  `fav_count` bigint unsigned DEFAULT '0',
  `coin_count` bigint unsigned DEFAULT '0',
  `comments_curated` tinyint(1) NOT NULL DEFAULT '0',
  `draft_raw_path` varchar(1024) DEFAULT NULL,
  `draft_cover_path` varchar(1024) DEFAULT NULL,
  `zone` varchar(64) DEFAULT NULL,
  `reviewed_at` datetime(3) DEFAULT NULL,
  `reviewed_by_admin_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_video_status` (`status`),
  KEY `idx_video_play` (`play_count`),
  KEY `idx_video_created` (`created_at`),
  KEY `idx_video_user` (`user_id`),
  KEY `idx_videos_reviewed_by_admin_id` (`reviewed_by_admin_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `watch_laters` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `video_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `watched` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_watch_later_user_video` (`user_id`,`video_id`),
  KEY `idx_watch_laters_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- +goose Down
-- Baseline rollback: drop all tables in reverse order.
DROP TABLE IF EXISTS `watch_laters`;
DROP TABLE IF EXISTS `videos`;
DROP TABLE IF EXISTS `video_view_histories`;
DROP TABLE IF EXISTS `video_likes`;
DROP TABLE IF EXISTS `video_favorites`;
DROP TABLE IF EXISTS `video_coins`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `user_search_histories`;
DROP TABLE IF EXISTS `user_follows`;
DROP TABLE IF EXISTS `user_follow_groups`;
DROP TABLE IF EXISTS `user_follow_group_members`;
DROP TABLE IF EXISTS `user_dynamics`;
DROP TABLE IF EXISTS `user_dynamic_likes`;
DROP TABLE IF EXISTS `user_daily_tasks`;
DROP TABLE IF EXISTS `user_blocks`;
DROP TABLE IF EXISTS `system_configs`;
DROP TABLE IF EXISTS `schema_versions`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `like_notif_mutes`;
DROP TABLE IF EXISTS `hot_search_ops`;
DROP TABLE IF EXISTS `hot_search_display_layouts`;
DROP TABLE IF EXISTS `home_banners`;
DROP TABLE IF EXISTS `favorite_folders`;
DROP TABLE IF EXISTS `dynamic_comments`;
DROP TABLE IF EXISTS `dynamic_comment_likes`;
DROP TABLE IF EXISTS `dynamic_comment_dislikes`;
DROP TABLE IF EXISTS `dm_participants`;
DROP TABLE IF EXISTS `dm_messages`;
DROP TABLE IF EXISTS `dm_conversations`;
DROP TABLE IF EXISTS `danmakus`;
DROP TABLE IF EXISTS `danmaku_likes`;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `comment_likes`;
DROP TABLE IF EXISTS `comment_dislikes`;
DROP TABLE IF EXISTS `coin_ledgers`;
DROP TABLE IF EXISTS `articles`;
DROP TABLE IF EXISTS `article_view_histories`;
DROP TABLE IF EXISTS `article_favorites`;
DROP TABLE IF EXISTS `article_comments`;
DROP TABLE IF EXISTS `article_comment_likes`;
DROP TABLE IF EXISTS `article_comment_dislikes`;
DROP TABLE IF EXISTS `article_coins`;
DROP TABLE IF EXISTS `agent_settings`;
DROP TABLE IF EXISTS `agent_profiles`;
DROP TABLE IF EXISTS `admins`;
