// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	agent "cakecake/internal/model/agent"
	dm "cakecake/internal/model/dm"
	serviceagent "cakecake/internal/service/agent"
	context "context"
	json "encoding/json"
)

// Agent is the client-side contract for cakecake/internal/service/agent.AgentService.
// Local implementation: serviceagent.AgentService (see the assertion below). A future gRPC client must implement this interface.
type Agent interface {
	CheckAgentSlugExists(ctx context.Context, slug string) (bool, error)
	CheckQuota(ctx context.Context, userID uint64) bool
	CountActiveAgentProfiles(ctx context.Context) (int64, error)
	CreateAgentBotUser(ctx context.Context, slug string, displayName string, sign string, avatarURL string) (uint64, error)
	CreateAgentProfile(ctx context.Context, p *agent.AgentProfile) error
	DeleteAgentProfile(ctx context.Context, id uint64) error
	EnsureAgentProfiles(ctx context.Context) error
	EnsureForUser(humanID uint64) error
	GenerateReply(ctx context.Context, conv *dm.DmConversation, userText string) (*serviceagent.GenerateReplyResult, error)
	GetAgentProfile(ctx context.Context, id uint64) (*agent.AgentProfile, error)
	GetGlobalSystemPrompt(ctx context.Context) string
	IncrQuota(ctx context.Context, userID uint64)
	IsAgentConversation(conv *dm.DmConversation) bool
	IsBotUser(uid uint64) bool
	ListAgentProfiles(ctx context.Context) ([]agent.AgentProfile, error)
	MaxProfiles() int
	NormalizeSlug(slug string) (string, error)
	PostAssistantMessage(conv *dm.DmConversation, humanID uint64, content string, extra ...string) (*dm.DmMessage, error)
	ProfileCount(ctx context.Context) (int64, error)
	ReloadProfiles()
	RenameAgentProfileSlug(ctx context.Context, p *agent.AgentProfile, newSlug string) error
	SyncAgentProfile(ctx context.Context, p *agent.AgentProfile) error
	UnmarshalWelcomeList(raw json.RawMessage, fallback []string) ([]string, error)
	UpdateAgentAvatar(ctx context.Context, id uint64, avatarURL string) error
	UpdateAgentProfile(ctx context.Context, id uint64, updates map[string]interface{}) error
}

var _ Agent = (*serviceagent.AgentService)(nil)
