// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	article "cakecake/internal/model/article"
	dbtx "cakecake/internal/pkg/dbtx"
	servicearticle "cakecake/internal/service/article"
	context "context"
)

// ArticleSvc is the client-side contract for cakecake/internal/service/article.ArticleService.
// Local implementation: servicearticle.ArticleService (see the assertion below). A future gRPC client must implement this interface.
type ArticleSvc interface {
	AdminDeleteArticleCascade(ctx context.Context, id uint64, fn func(tx dbtx.Tx) error) error
	AdminListArticles(ctx context.Context, statuses []string, titleQ string, page int, pageSize int) (*servicearticle.AdminListArticlesResult, error)
	AdminUpdateArticle(ctx context.Context, id uint64, updates map[string]interface{}) error
	BatchArticleEngagementByViewer(ctx context.Context, viewerID uint64, articleIDs []uint64) map[uint64]*servicearticle.ArticleEngagement
	BatchFetchArticles(ctx context.Context, ids []uint64, onlyPublished bool) map[uint64]*article.Article
	CountArticlesByStatus(ctx context.Context, userID uint64) map[string]int64
	CountFavoritedArticles(ctx context.Context, userID uint64, onlyPublished bool) (int64, error)
	CreateArticle(ctx context.Context, art *article.Article) error
	DeleteArticle(ctx context.Context, id uint64) error
	GetArticleByID(ctx context.Context, id uint64) (*article.Article, error)
	GetOwnedArticle(ctx context.Context, id uint64, userID uint64) (*article.Article, error)
	GetPublishedArticle(ctx context.Context, id uint64) (*article.Article, error)
	IncrementArticleView(ctx context.Context, id uint64) error
	ListFavoritedArticlesV2(ctx context.Context, userID uint64, cursor uint64, limit int) ([]article.ArticleFavorite, bool, error)
	ListMyArticlesPage(ctx context.Context, userID uint64, page int, pageSize int, status string, titleQ string, sortKey string) (*servicearticle.ListMyArticlesPageResult, error)
	ListUserPublishedArticlesCursor(ctx context.Context, userID uint64, cursor uint64, limit int) (*servicearticle.ListArticlesCursorResult, error)
	PostArticleCoin(ctx context.Context, userID uint64, articleID uint64, amount int) (*servicearticle.PostArticleCoinResult, error)
	Publish(ctx context.Context, articleID uint64, adminID *uint64) error
	ToggleArticleFavorite(ctx context.Context, userID uint64, articleID uint64) (bool, uint64, error)
	UpdateArticle(ctx context.Context, id uint64, updates map[string]interface{}) error
}

var _ ArticleSvc = (*servicearticle.ArticleService)(nil)
