// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	admin "cakecake/internal/model/admin"
	user "cakecake/internal/service/user"
	context "context"
	time "time"
)

// AuthSvc is the client-side contract for cakecake/internal/service/user.AuthService.
// Local implementation: user.AuthService (see the assertion below). A future gRPC client must implement this interface.
type AuthSvc interface {
	AdminRefreshTokenInvalid(ctx context.Context, tokenID string) bool
	Authenticate(ctx context.Context, userID uint64, password string) (*user.AuthenticateResult, error)
	FindAdminByUsername(ctx context.Context, username string) (*admin.Admin, error)
	GetAdminByID(ctx context.Context, id uint64) (*admin.Admin, error)
	LookupUser(ctx context.Context, reqUsername string) (*user.UserBrief, error)
	Logout(ctx context.Context, refreshToken string) error
	MarkAdminRefreshTokenInvalid(ctx context.Context, tokenID string) error
	Refresh(ctx context.Context, refreshToken string) (*user.RefreshResult, error)
	Register(ctx context.Context, reqUsername string, reqPassword string) (*user.RegisterResult, error)
	UpdateAdminLoginTime(ctx context.Context, id uint64, t time.Time) error
}

var _ AuthSvc = (*user.AuthService)(nil)
