// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	admin "cakecake/internal/model/admin"
	banner "cakecake/internal/service/banner"
	context "context"
)

// BannerSvc is the client-side contract for cakecake/internal/service/banner.BannerService.
// Local implementation: banner.BannerService (see the assertion below). A future gRPC client must implement this interface.
type BannerSvc interface {
	CreateBanner(ctx context.Context, b *admin.HomeBanner) error
	DeleteBanner(ctx context.Context, id uint64) error
	GetBanner(ctx context.Context, id uint64) (*admin.HomeBanner, error)
	ListActiveBanners(ctx context.Context) ([]admin.HomeBanner, error)
	ListBanners(ctx context.Context) ([]admin.HomeBanner, error)
	UpdateBanner(ctx context.Context, id uint64, updates map[string]interface{}) error
}

var _ BannerSvc = (*banner.BannerService)(nil)
