// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	comment "cakecake/internal/model/comment"
	servicecomment "cakecake/internal/service/comment"
	context "context"
)

// CommentSvc is the client-side contract for cakecake/internal/service/comment.CommentService.
// Local implementation: servicecomment.CommentService (see the assertion below). A future gRPC client must implement this interface.
type CommentSvc interface {
	ApproveArticleComment(ctx context.Context, commentID uint64) error
	ApproveComment(ctx context.Context, commentID uint64) error
	ApproveDynComment(ctx context.Context, commentID uint64) error
	DeleteArticleComment(ctx context.Context, userID uint64, commentID uint64, isAuthor bool) error
	DeleteComment(ctx context.Context, userID uint64, commentID uint64, isUploader bool) error
	DeleteDynamicComment(ctx context.Context, userID uint64, commentID uint64, isUploader bool) error
	GetArticleComment(ctx context.Context, commentID uint64) (*comment.ArticleComment, error)
	GetCommentByID(ctx context.Context, commentID uint64) (*comment.Comment, error)
	GetDynamicCommentByID(ctx context.Context, commentID uint64) (*comment.DynamicComment, error)
	IgnoreArticleComment(ctx context.Context, commentID uint64) error
	IgnoreCuratedComment(ctx context.Context, commentID uint64) error
	IgnoreDynComment(ctx context.Context, commentID uint64) error
	ListArticleComments(ctx context.Context, articleID uint64, viewerID uint64) (*servicecomment.CommentListResult, error)
	ListComments(ctx context.Context, videoID uint64, viewerID uint64) (*servicecomment.CommentListResult, error)
	ListDynamicComments(ctx context.Context, dynamicID uint64, viewerID uint64) (*servicecomment.CommentListResult, error)
	PinArticleComment(ctx context.Context, articleID uint64, commentID uint64) (bool, error)
	PinComment(ctx context.Context, videoID uint64, commentID uint64) (bool, error)
	PostArticleComment(ctx context.Context, userID uint64, articleID uint64, req servicecomment.PostCommentReq, ipLocation string) (*comment.ArticleComment, error)
	PostComment(ctx context.Context, userID uint64, videoID uint64, req servicecomment.PostCommentReq, ipLocation string) (*comment.Comment, error)
	PostDynamicComment(ctx context.Context, userID uint64, dynamicID uint64, req servicecomment.PostCommentReq, ipLocation string) (*comment.DynamicComment, error)
	ToggleArticleCommentDislike(ctx context.Context, userID uint64, commentID uint64) (bool, error)
	ToggleArticleCommentLike(ctx context.Context, userID uint64, commentID uint64) (bool, int, error)
	ToggleCommentDislike(ctx context.Context, userID uint64, commentID uint64) (bool, error)
	ToggleCommentLike(ctx context.Context, userID uint64, commentID uint64) (bool, int, error)
	ToggleDynamicCommentReaction(ctx context.Context, userID uint64, commentID uint64, like bool) (bool, int, error)
}

var _ CommentSvc = (*servicecomment.CommentService)(nil)
