// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	article "cakecake/internal/model/article"
	comment "cakecake/internal/model/comment"
	dynamic "cakecake/internal/model/dynamic"
	user "cakecake/internal/model/user"
	video "cakecake/internal/model/video"
	servicecomment "cakecake/internal/service/comment"
	context "context"
)

// CreatorCommentSvc is the client-side contract for cakecake/internal/service/comment.CreatorCommentService.
// Local implementation: servicecomment.CreatorCommentService (see the assertion below). A future gRPC client must implement this interface.
type CreatorCommentSvc interface {
	ArticleCommentReplyCounts(ctx context.Context, ids []uint64) map[uint64]uint64
	BatchFetchArticleComments(ctx context.Context, ids []uint64) (map[uint64]comment.ArticleComment, error)
	BatchFetchArticles(ctx context.Context, ids []uint64) (map[uint64]article.Article, error)
	BatchFetchComments(ctx context.Context, ids []uint64) (map[uint64]comment.Comment, error)
	BatchFetchDynamicComments(ctx context.Context, ids []uint64) (map[uint64]comment.DynamicComment, error)
	BatchFetchDynamics(ctx context.Context, ids []uint64) (map[uint64]dynamic.UserDynamic, error)
	BatchFetchUsers(ctx context.Context, ids []uint64) (map[uint64]user.User, error)
	BatchFetchVideos(ctx context.Context, ids []uint64) (map[uint64]video.Video, error)
	CommentReplyCounts(ctx context.Context, ids []uint64) map[uint64]uint64
	DynamicCommentReplyCounts(ctx context.Context, ids []uint64) map[uint64]uint64
	ListCreatorArticleComments(ctx context.Context, q servicecomment.CreatorArticleCommentQuery) (*servicecomment.CreatorArticleCommentResult, error)
	ListCreatorDynamicComments(ctx context.Context, q servicecomment.CreatorDynamicCommentQuery) (*servicecomment.CreatorDynamicCommentResult, error)
	ListCreatorVideoComments(ctx context.Context, q servicecomment.CreatorVideoCommentQuery) (*servicecomment.CreatorVideoCommentResult, error)
}

var _ CreatorCommentSvc = (*servicecomment.CreatorCommentService)(nil)
