// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	dailyreward "cakecake/internal/pkg/dailyreward"
	servicedailyreward "cakecake/internal/service/dailyreward"
)

// DailyRewardSvc is the client-side contract for cakecake/internal/service/dailyreward.DailyRewardService.
// Local implementation: servicedailyreward.DailyRewardService (see the assertion below). A future gRPC client must implement this interface.
type DailyRewardSvc interface {
	BuildSnapshot(uid uint64) (dailyreward.RewardsSnapshot, error)
	CoinProgress(uid uint64) int
	MarkLogin(uid uint64) error
	MarkWatch(uid uint64) error
}

var _ DailyRewardSvc = (*servicedailyreward.DailyRewardService)(nil)
