// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	danmaku "cakecake/internal/model/danmaku"
	servicedanmaku "cakecake/internal/service/danmaku"
	context "context"
)

// DanmakuSvc is the client-side contract for cakecake/internal/service/danmaku.DanmakuService.
// Local implementation: servicedanmaku.DanmakuService (see the assertion below). A future gRPC client must implement this interface.
type DanmakuSvc interface {
	DeleteCreatorDanmaku(ctx context.Context, uid uint64, danmakuID uint64) (*danmaku.Danmaku, error)
	ListCreatorDanmakus(ctx context.Context, uid uint64, limit int, keyword string, typeFilter string, filterVideoID uint64, viewerID uint64) (*servicedanmaku.ListCreatorDanmakusResult, error)
	ListHistory(ctx context.Context, videoID uint64, currentTime float64, limit int) ([]danmaku.Danmaku, error)
	PostDanmaku(ctx context.Context, videoID uint64, userID uint64, content string, color string, danmakuType string, fontSize string, videoTime float64) (*servicedanmaku.DanmakuPostResult, error)
	ToggleDanmakuLike(ctx context.Context, danmakuID uint64, userID uint64) (*servicedanmaku.ToggleDanmakuLikeResult, error)
}

var _ DanmakuSvc = (*servicedanmaku.DanmakuService)(nil)
