// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	dm "cakecake/internal/model/dm"
	servicedm "cakecake/internal/service/dm"
	context "context"
)

// DmSvc is the client-side contract for cakecake/internal/service/dm.DmService.
// Local implementation: servicedm.DmService (see the assertion below). A future gRPC client must implement this interface.
type DmSvc interface {
	DeleteConversation(ctx context.Context, convID uint64, userID uint64) error
	FindConversationByUserIDs(ctx context.Context, uidA uint64, uidB uint64) (*dm.DmConversation, error)
	GetConversationByID(ctx context.Context, convID uint64) (*dm.DmConversation, error)
	GetOrCreateConversation(ctx context.Context, uid uint64, peerID uint64) (*dm.DmConversation, *dm.DmParticipant, error)
	GetParticipant(ctx context.Context, convID uint64, userID uint64) (*dm.DmParticipant, error)
	ListConversations(ctx context.Context, uid uint64) ([]dm.DmConversation, []dm.DmParticipant, error)
	ListMessages(ctx context.Context, convID uint64, beforeID uint64, limit int) ([]dm.DmMessage, error)
	MarkConversationRead(ctx context.Context, convID uint64, userID uint64) error
	PostMessage(ctx context.Context, convID uint64, senderID uint64, peerID uint64, content string, preview string, isAgent bool) (*servicedm.PostMessageResult, error)
	ResetConversationForAgent(ctx context.Context, convID uint64) error
	UnreadTotal(ctx context.Context, uid uint64) int64
	UpdateConversationSettings(ctx context.Context, convID uint64, userID uint64, updates map[string]interface{}) error
}

var _ DmSvc = (*servicedm.DmService)(nil)
