// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	dynamic "cakecake/internal/model/dynamic"
	servicedynamic "cakecake/internal/service/dynamic"
	context "context"
	gorm "gorm.io/gorm"
)

// DynamicSvc is the client-side contract for cakecake/internal/service/dynamic.DynamicService.
// Local implementation: servicedynamic.DynamicService (see the assertion below). A future gRPC client must implement this interface.
type DynamicSvc interface {
	AdminDeleteDynamicCascade(ctx context.Context, id uint64, fn func(tx *gorm.DB) error) error
	AdminListDynamics(ctx context.Context, q string, page int, pageSize int) (*servicedynamic.AdminListDynamicsResult, error)
	BatchCheckLiked(ctx context.Context, viewerID uint64, dynamicIDs []uint64) map[uint64]bool
	CountUserDynamics(ctx context.Context, userID uint64) (int64, error)
	CreateDynamic(ctx context.Context, d *dynamic.UserDynamic) error
	DeleteDynamic(ctx context.Context, id uint64) error
	GetDynamicByID(ctx context.Context, id uint64) (*dynamic.UserDynamic, error)
	ListMyDynamicsAdvanced(ctx context.Context, f servicedynamic.MyDynamicFilter) (*servicedynamic.MyDynamicPageResult, error)
	ListUserDynamicsCursor(ctx context.Context, userID uint64, cursorID uint64, limit int) ([]dynamic.UserDynamic, error)
	ToggleDynamicLike(ctx context.Context, userID uint64, dynamicID uint64) (bool, error)
	UpdateDynamic(ctx context.Context, id uint64, updates map[string]interface{}) error
}

var _ DynamicSvc = (*servicedynamic.DynamicService)(nil)
