// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	engagement "cakecake/internal/service/engagement"
	context "context"
)

// EngagementSvc is the client-side contract for cakecake/internal/service/engagement.EngagementService.
// Local implementation: engagement.EngagementService (see the assertion below). A future gRPC client must implement this interface.
type EngagementSvc interface {
	BatchCoinedByUser(ctx context.Context, userID uint64, videoIDs []uint64) map[uint64]int
	BatchVideoLikes(ctx context.Context, userID uint64, videoIDs []uint64) map[uint64]bool
	BatchWatchLater(ctx context.Context, userID uint64, videoIDs []uint64) map[uint64]bool
	ClearWatchLater(ctx context.Context, userID uint64) error
	ClearWatchedWatchLater(ctx context.Context, userID uint64) error
	ListUserCoinedVideos(ctx context.Context, ownerID uint64, limit int) ([]engagement.CoinedVideoItem, int64, error)
	ListWatchLaterWithVideos(ctx context.Context, userID uint64, page int, pageSize int) ([]engagement.WatchLaterVideoItem, int64, error)
	MarkWatchLaterWatched(ctx context.Context, userID uint64, videoID uint64) error
	PostVideoCoin(ctx context.Context, uid uint64, vid uint64, uploaderID uint64, amount int) (*engagement.PostVideoCoinResult, error)
	ToggleWatchLater(ctx context.Context, userID uint64, videoID uint64) (bool, error)
}

var _ EngagementSvc = (*engagement.EngagementService)(nil)
