// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	video "cakecake/internal/model/video"
	favorite "cakecake/internal/service/favorite"
	context "context"
)

// FavoriteSvc is the client-side contract for cakecake/internal/service/favorite.FavoriteService.
// Local implementation: favorite.FavoriteService (see the assertion below). A future gRPC client must implement this interface.
type FavoriteSvc interface {
	AddFavorite(ctx context.Context, folderID uint64, videoID uint64, userID uint64) error
	AdjustVideoFavCount(ctx context.Context, videoID uint64, delta int) error
	BatchFavorited(ctx context.Context, userID uint64, videoIDs []uint64) map[uint64]bool
	CheckFavoriteExists(ctx context.Context, userID uint64, folderID uint64, videoID uint64) (bool, error)
	CountFavoritesInFolder(ctx context.Context, folderID uint64) (int64, error)
	CountFoldersByUser(ctx context.Context, userID uint64) (int64, error)
	CountPublicFoldersByUser(ctx context.Context, userID uint64) (int64, error)
	CreateFolder(ctx context.Context, folder *video.FavoriteFolder) error
	DeleteFavoriteByVideo(ctx context.Context, userID uint64, folderID uint64, videoID uint64) error
	DeleteFolder(ctx context.Context, id uint64) error
	DeleteFolderCascade(ctx context.Context, folderID uint64, userID uint64) error
	FilterPublishedVideoIDs(ctx context.Context, videoIDs []uint64) ([]uint64, error)
	FolderCoverFromVideos(ctx context.Context, folderID uint64) string
	GetFolderByID(ctx context.Context, id uint64) (*video.FavoriteFolder, error)
	ListFavoritesByFolder(ctx context.Context, folderID uint64, page int, pageSize int) ([]video.VideoFavorite, int64, error)
	ListFoldersByUser(ctx context.Context, userID uint64) ([]video.FavoriteFolder, error)
	ListUserFavoriteVideos(ctx context.Context, ownerID uint64, limit int, folderID uint64, filterFolder bool) (*favorite.UserFavoriteVideoResult, error)
	MigrateOrphanFavorites(ctx context.Context, userID uint64, targetFolderID uint64) error
	RemoveFavorite(ctx context.Context, folderID uint64, videoID uint64) error
	SetVideoFavoriteFolders(ctx context.Context, userID uint64, videoID uint64, wantedIDs []uint64) (*favorite.SetVideoFavoriteFoldersResult, error)
	ToggleVideoFavoriteWithFolder(ctx context.Context, userID uint64, videoID uint64, folderID uint64) (bool, uint64, error)
	UpdateFolder(ctx context.Context, id uint64, updates map[string]interface{}) error
	UpdateFolderCover(ctx context.Context, folderID uint64, coverURL string) error
	UserFavoriteCount(ctx context.Context, userID uint64, videoID uint64) (int64, error)
}

var _ FavoriteSvc = (*favorite.FavoriteService)(nil)
