// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	user "cakecake/internal/model/user"
	follow "cakecake/internal/service/follow"
	context "context"
)

// FollowSvc is the client-side contract for cakecake/internal/service/follow.FollowService.
// Local implementation: follow.FollowService (see the assertion below). A future gRPC client must implement this interface.
type FollowSvc interface {
	AddGroupMember(ctx context.Context, groupID uint64, followeeID uint64) error
	BlockUser(ctx context.Context, uid uint64, targetID uint64) error
	CreateGroup(ctx context.Context, userID uint64, name string) (*user.UserFollowGroup, error)
	DeleteGroup(ctx context.Context, userID uint64, groupID uint64) error
	GetFollowCounts(ctx context.Context, userID uint64) (follow.FollowCounts, error)
	GetFolloweeGroupIDs(ctx context.Context, userID uint64, followeeID uint64) ([]uint64, error)
	GetFollowersList(ctx context.Context, ownerID uint64, limit int) ([]user.UserFollow, error)
	GetFollowingIDs(ctx context.Context, followerID uint64, candidateIDs []uint64) (map[uint64]bool, error)
	GetFollowingList(ctx context.Context, ownerID uint64, limit int, groupID uint64) ([]user.UserFollow, error)
	GetGroup(ctx context.Context, userID uint64, groupID uint64) (*user.UserFollowGroup, error)
	GetGroupMemberCounts(ctx context.Context, groupIDs []uint64) (map[uint64]int64, error)
	GetUploaderPublishedCount(ctx context.Context, userID uint64) (int64, error)
	IsFollowing(ctx context.Context, followerID uint64, followeeID uint64) (bool, error)
	ListGroups(ctx context.Context, userID uint64) ([]user.UserFollowGroup, error)
	RemoveGroupMember(ctx context.Context, groupID uint64, followeeID uint64) error
	ToggleFollow(ctx context.Context, followerID uint64, followeeID uint64) (bool, error)
	UnblockUser(ctx context.Context, uid uint64, targetID uint64) error
	UpdateGroup(ctx context.Context, userID uint64, groupID uint64, name string) (*user.UserFollowGroup, error)
	UsersBlocked(ctx context.Context, a uint64, b uint64) (bool, error)
}

var _ FollowSvc = (*follow.FollowService)(nil)
