// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	admin "cakecake/internal/model/admin"
	hotsearch "cakecake/internal/service/hotsearch"
	context "context"
)

// HotSearchSvc is the client-side contract for cakecake/internal/service/hotsearch.HotSearchService.
// Local implementation: hotsearch.HotSearchService (see the assertion below). A future gRPC client must implement this interface.
type HotSearchSvc interface {
	ActiveOpFlags(ctx context.Context) map[string]hotsearch.HotSearchOpFlags
	BoostKeyword(ctx context.Context, keyword string, delta float64) error
	ClearDisplayLayout(ctx context.Context) error
	CreateOp(ctx context.Context, op *admin.HotSearchOp) error
	DeleteOp(ctx context.Context, id uint64) error
	GetOp(ctx context.Context, id uint64) (*admin.HotSearchOp, error)
	HasDisplayLayout(ctx context.Context) bool
	ListMerged(ctx context.Context, limit int) ([]hotsearch.HotSearchItem, error)
	ListMergedDetail(ctx context.Context, limit int) ([]hotsearch.HotSearchMergedDetail, error)
	ListOps(ctx context.Context) ([]admin.HotSearchOp, error)
	QuickOpCreateOrUpdate(ctx context.Context, opType string, keyword string, displayTitle string, badge string, pinRank int) (*admin.HotSearchOp, bool, error)
	RemoveKeywordFromRedis(ctx context.Context, keyword string) error
	ReorderItems(ctx context.Context, items []hotsearch.ReorderItem) error
	SearchSuggest(ctx context.Context, userID uint64, term string, limit int) []hotsearch.SearchSuggestTag
	TopWithScores(ctx context.Context, limit int) ([]hotsearch.HotSearchRedisRow, error)
	UpdateOp(ctx context.Context, id uint64, updates map[string]any) error
	ValidateSuggestTerm(term string) bool
}

var _ HotSearchSvc = (*hotsearch.HotSearchService)(nil)
