// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	notification "cakecake/internal/model/notification"
	service "cakecake/internal/service"
	servicenotification "cakecake/internal/service/notification"
	context "context"
)

// NotifSvc is the client-side contract for cakecake/internal/service/notification.NotificationService.
// Local implementation: servicenotification.NotificationService (see the assertion below). A future gRPC client must implement this interface.
type NotifSvc interface {
	DeleteNotification(ctx context.Context, userID uint64, notifID uint64) error
	GetNotification(ctx context.Context, notifID uint64, userID uint64) (*notification.Notification, error)
	ListNotificationLikers(ctx context.Context, userID uint64, notifID uint64) ([]service.UserInfo, error)
	ListNotifications(ctx context.Context, userID uint64, cat string, page int, pageSize int) ([]notification.Notification, int64, error)
	MarkCategoryRead(ctx context.Context, userID uint64, cat string) error
	MarkNotificationsRead(ctx context.Context, userID uint64, ids []uint64) error
	MuteLikeNotification(ctx context.Context, userID uint64, notifID uint64) error
	UnreadSummary(ctx context.Context, userID uint64) map[string]int64
}

var _ NotifSvc = (*servicenotification.NotificationService)(nil)
