// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	search "cakecake/internal/search"
	servicesearch "cakecake/internal/service/search"
	context "context"
	time "time"
)

// SearchSvc is the client-side contract for cakecake/internal/service/search.SearchService.
// Local implementation: servicesearch.SearchService (see the assertion below). A future gRPC client must implement this interface.
type SearchSvc interface {
	CacheGet(ctx context.Context, key string) (string, error)
	CacheSet(ctx context.Context, key string, value string, ttl time.Duration) error
	DeleteArticle(ctx context.Context, articleID uint64) error
	DeleteVideo(ctx context.Context, videoID uint64) error
	Enabled() bool
	EnrichUserHits(ctx context.Context, viewer uint64, hits []search.UserHit) []search.UserHit
	IndexArticleFromDB(ctx context.Context, articleID uint64) error
	IndexUserFromDB(ctx context.Context, userID uint64) error
	IndexVideoFromDB(ctx context.Context, videoID uint64) error
	SearchAll(ctx context.Context, params search.SearchParams) (*search.AllResult, error)
}

var _ SearchSvc = (*servicesearch.SearchService)(nil)
