// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	search "cakecake/internal/service/search"
	context "context"
	time "time"
)

// SearchHistorySvc is the client-side contract for cakecake/internal/service/search.SearchHistoryService.
// Local implementation: search.SearchHistoryService (see the assertion below). A future gRPC client must implement this interface.
type SearchHistorySvc interface {
	ListKeywords(ctx context.Context, uid uint64) ([]string, error)
	ReplaceHistory(ctx context.Context, uid uint64, keywords []string) error
	TrimHistory(ctx context.Context, uid uint64) error
	UpsertKeyword(ctx context.Context, uid uint64, kw string, at time.Time) error
}

var _ SearchHistorySvc = (*search.SearchHistoryService)(nil)
