// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	admin "cakecake/internal/model/admin"
	article "cakecake/internal/model/article"
	dynamic "cakecake/internal/model/dynamic"
	video "cakecake/internal/model/video"
	storage "cakecake/internal/service/storage"
	io "io"
)

// StorageSvc is the client-side contract for cakecake/internal/service/storage.StorageService.
// Local implementation: storage.StorageService (see the assertion below). A future gRPC client must implement this interface.
type StorageSvc interface {
	Enabled() bool
	PurgeAgentAvatar(avatarURL string)
	PurgeArticle(art article.Article)
	PurgeBanner(b admin.HomeBanner)
	PurgeBannerImageURL(imageURL string)
	PurgeDynamic(dyn dynamic.UserDynamic)
	PurgeFavoriteFolder(f video.FavoriteFolder)
	PurgeFavoriteFolderCoverURL(coverURL string, uid uint64, folderID uint64)
	PurgeRemovedDynamicImageURLs(oldURLs []string, newURLs []string)
	PurgeVideo(v video.Video)
	UploadFile(objectKey string, localPath string) error
	UploadReader(objectKey string, r io.Reader) error
}

var _ StorageSvc = (*storage.StorageService)(nil)
