// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	user "cakecake/internal/model/user"
	serviceuser "cakecake/internal/service/user"
	context "context"
	gorm "gorm.io/gorm"
	time "time"
)

// UserSvc is the client-side contract for cakecake/internal/service/user.UserService.
// Local implementation: serviceuser.UserService (see the assertion below). A future gRPC client must implement this interface.
type UserSvc interface {
	BatchGetUsers(ctx context.Context, userIDs []uint64) map[uint64]*user.User
	EnsureCakeID(ctx context.Context, u *user.User) error
	FinalizeDeletion(ctx context.Context, uid uint64, fn func(tx *gorm.DB) error) error
	GetMe(ctx context.Context, userID uint64) (*serviceuser.UserProfile, error)
	GetPasswordHash(ctx context.Context, userID uint64) (string, error)
	GetPrivacySettings(ctx context.Context, userID uint64) (*user.User, error)
	GetUserBrief(ctx context.Context, userID uint64) (name string, avatar string, err error)
	GetUserByID(ctx context.Context, userID uint64) (*user.User, error)
	GetUserPublic(ctx context.Context, userID uint64) (*serviceuser.UserProfile, error)
	ListCoinLedger(ctx context.Context, userID uint64, since time.Time, limit int, offset int) (total int64, rows []user.CoinLedger, err error)
	RequestDeletion(ctx context.Context, userID uint64, requestedAt time.Time, effectiveAt time.Time) error
	RevokeDeletion(ctx context.Context, userID uint64) error
	UpdateAnnouncement(ctx context.Context, userID uint64, announcement string) error
	UpdateAvatar(ctx context.Context, userID uint64, objectKey string) error
	UpdatePassword(ctx context.Context, userID uint64, newHash string) error
	UpdatePrivacySettings(ctx context.Context, userID uint64, updates map[string]interface{}) error
	UpdateProfile(ctx context.Context, userID uint64, updates map[string]interface{}) error
	UpdateUsername(ctx context.Context, userID uint64, newName string) error
}

var _ UserSvc = (*serviceuser.UserService)(nil)
