// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	video "cakecake/internal/model/video"
	dbtx "cakecake/internal/pkg/dbtx"
	servicevideo "cakecake/internal/service/video"
	context "context"
)

// VideoSvc is the client-side contract for cakecake/internal/service/video.VideoService.
// Local implementation: servicevideo.VideoService (see the assertion below). A future gRPC client must implement this interface.
type VideoSvc interface {
	AdminDeleteVideoCascade(ctx context.Context, id uint64, fn func(tx dbtx.Tx) error) error
	AdminListVideos(ctx context.Context, statuses []string, titleQ string, page int, pageSize int) (*servicevideo.AdminListVideosResult, error)
	AdminUpdateVideo(ctx context.Context, id uint64, updates map[string]interface{}) error
	CountMyVideosByStatus(uid uint64) map[string]int64
	CountPublishedVideos(ctx context.Context) int64
	CountZoneVideos(zoneParent string) int64
	CreateVideoRecord(ctx context.Context, v *video.Video) error
	CreateDirectUploadTicket(ctx context.Context, uid uint64, filename string, coverFilename string) (*servicevideo.DirectUploadTicket, error)
	CreateVideoFromDirectUpload(ctx context.Context, uid uint64, title string, description string, tagsJSON string, zone string, rawKey string, coverKey string) (*video.Video, error)
	DeleteVideoByID(ctx context.Context, id uint64) error
	DeleteVideoWithCascade(ctx context.Context, id uint64, fn func(tx dbtx.Tx) error) error
	EnqueueTranscode(ctx context.Context, videoID uint64, rawPath string, coverPath string) error
	FFprobeExe() string
	GetPublishedVideo(ctx context.Context, id uint64) (*video.Video, error)
	GetVideoByID(ctx context.Context, id uint64) (*video.Video, error)
	HumanizeFailReason(reason string) string
	ListMyVideosAdvanced(ctx context.Context, f servicevideo.MyVideoFilter) (*servicevideo.MyVideoPageResult, error)
	ListPublishedVideos(ctx context.Context, opts servicevideo.VideoListOpts) (*servicevideo.VideoListResult, error)
	ListUserPublishedVideosCursor(ctx context.Context, uid uint64, cursorID uint64, limit int) ([]video.Video, error)
	ListTranscodeDeadLetters(ctx context.Context, f servicevideo.TranscodeDeadLetterFilter) ([]video.TranscodeDeadLetter, int64, error)
	ProbeDurationSeconds(path string) (float64, error)
	Publish(ctx context.Context, videoID uint64, adminID *uint64) error
	RequeueTranscodeDeadLetter(ctx context.Context, id uint64) error
	ToggleVideoLike(ctx context.Context, userID uint64, videoID uint64) (bool, error)
	UpdateVideo(ctx context.Context, v *video.Video, updates map[string]interface{}) error
}

var _ VideoSvc = (*servicevideo.VideoService)(nil)
