// Code generated by internal/client contract generator; DO NOT EDIT.

package client

import (
	article "cakecake/internal/model/article"
	extra "cakecake/internal/model/extra"
	user "cakecake/internal/model/user"
	video "cakecake/internal/model/video"
	viewhistory "cakecake/internal/service/viewhistory"
	context "context"
	time "time"
)

// ViewHistorySvc is the client-side contract for cakecake/internal/service/viewhistory.ViewHistoryService.
// Local implementation: viewhistory.ViewHistoryService (see the assertion below). A future gRPC client must implement this interface.
type ViewHistorySvc interface {
	BatchFetchArticlesByIDs(ctx context.Context, ids []uint64) (map[uint64]article.Article, error)
	BatchFetchUsersByIDs(ctx context.Context, ids []uint64) (map[uint64]user.User, error)
	BatchFetchVideosByIDs(ctx context.Context, ids []uint64) (map[uint64]video.Video, error)
	ClearArticleViewHistory(ctx context.Context, userID uint64) error
	ClearViewHistory(ctx context.Context, userID uint64) error
	DeleteArticleHistoryByArticle(ctx context.Context, userID uint64, articleID uint64) error
	DeleteVideoHistoryByVideo(ctx context.Context, userID uint64, videoID uint64) error
	GetUserViewHistoryPaused(ctx context.Context, userID uint64) (bool, error)
	GetViewHistorySettings(ctx context.Context, userID uint64) (bool, error)
	ListArticleViewHistory(ctx context.Context, userID uint64, keyword string) ([]extra.ArticleViewHistory, error)
	ListVideoViewHistory(ctx context.Context, userID uint64, keyword string) ([]extra.VideoViewHistory, error)
	RecordArticleViewHistory(ctx context.Context, userID uint64, articleID uint64, device string)
	RecordVideoViewHistoryWithProgress(ctx context.Context, userID uint64, videoID uint64, progressSec float64, durationSec float64, device string, viewedAt time.Time) error
	TrimViewHistoryCombined(ctx context.Context, userID uint64, maxItems int)
	UpdateViewHistorySettings(ctx context.Context, userID uint64, paused bool) error
}

var _ ViewHistorySvc = (*viewhistory.ViewHistoryService)(nil)
