package main

import (
	"database/sql"
	"fmt"
	"os"
	"sort"
	"strings"

	_ "github.com/go-sql-driver/mysql"
	"github.com/joho/godotenv"
)

var gooseInternal = map[string]bool{
	"goose_db_version": true,
}

func main() {
	_ = godotenv.Load()
	dsn := os.Getenv("MYSQL_DSN")
	if dsn == "" {
		fmt.Fprintln(os.Stderr, "MYSQL_DSN not set")
		os.Exit(1)
	}

	db, err := sql.Open("mysql", dsn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "connect: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		fmt.Fprintf(os.Stderr, "ping: %v\n", err)
		os.Exit(1)
	}

	rows, err := db.Query("SHOW TABLES")
	if err != nil {
		fmt.Fprintf(os.Stderr, "tables: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			continue
		}
		if gooseInternal[t] {
			continue
		}
		tables = append(tables, t)
	}
	sort.Strings(tables)

	fmt.Println("-- +goose Up")
	fmt.Println("-- Baseline DDL: all domain tables exported from MySQL via SHOW CREATE TABLE.")
	fmt.Println("-- Goose internal tables (goose_db_version) excluded — goose manages those.")
	fmt.Println("-- Generated by: go run scripts/export_baseline.go > migrations/00001_baseline.sql")
	fmt.Println()

	for _, table := range tables {
		var name, ddl string
		if err := db.QueryRow("SHOW CREATE TABLE `"+table+"`").Scan(&name, &ddl); err != nil {
			fmt.Fprintf(os.Stderr, "skip %s: %v\n", table, err)
			continue
		}
		ddl = strings.Replace(ddl, "CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", 1)
		ddl = strings.ReplaceAll(ddl, "utf8mb4_0900_ai_ci", "utf8mb4_general_ci")
		fmt.Printf("%s;\n\n", ddl)
	}

	fmt.Println("-- +goose Down")
	fmt.Println("-- Baseline rollback: drop all tables in reverse order.")
	for i := len(tables) - 1; i >= 0; i-- {
		fmt.Printf("DROP TABLE IF EXISTS `%s`;\n", tables[i])
	}
}
